/**
 * PDF Exporter
 * Exports slides to styled PDF format using @react-pdf/renderer
 */
import React from 'react';
import { pdf, Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import type { Session, ParsedSlide } from '@/types/slidePrompt';
import { sanitizeFilename } from '@/lib/utils/sanitize-filename';

// PDF styles
const styles = StyleSheet.create({
  page: {
    padding: 40,
    backgroundColor: '#ffffff',
  },
  titlePage: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mainTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#1a1a1a',
    textAlign: 'center',
    marginBottom: 20,
  },
  subtitle: {
    fontSize: 12,
    color: '#666666',
    textAlign: 'center',
  },
  slideContainer: {
    marginBottom: 30,
  },
  slideHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    paddingBottom: 8,
    borderBottomWidth: 2,
    borderBottomColor: '#e5e5e5',
  },
  slideNumber: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#ffffff',
    backgroundColor: '#3b82f6',
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 4,
    marginRight: 12,
  },
  slideTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1a1a1a',
    flex: 1,
  },
  slideContent: {
    fontSize: 11,
    color: '#374151',
    lineHeight: 1.6,
  },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 40,
    right: 40,
    fontSize: 9,
    color: '#9ca3af',
    textAlign: 'center',
  },
  pageNumber: {
    position: 'absolute',
    bottom: 20,
    right: 40,
    fontSize: 9,
    color: '#9ca3af',
  },
});

interface SlideDocumentProps {
  session: Session;
  slides: ParsedSlide[];
}

/**
 * PDF Document component for slides
 * Each slide gets its own page for better readability (Fix: PERF page breaks)
 */
function SlideDocument({ session, slides }: SlideDocumentProps): React.ReactElement {
  return React.createElement(
    Document,
    {
      title: session.title,
      author: 'Nano Banana Slides Prompter',
      subject: 'AI-Generated Slide Prompts',
    },
    // Title page
    React.createElement(
      Page,
      { size: 'A4', style: styles.page },
      React.createElement(
        View,
        { style: styles.titlePage },
        React.createElement(Text, { style: styles.mainTitle }, session.title),
        React.createElement(
          Text,
          { style: styles.subtitle },
          `${slides.length} Slides • Generated by Nano Banana Slides Prompter`
        )
      )
    ),
    // Content pages - one page per slide for better page breaks
    ...slides.map((slide) =>
      React.createElement(
        Page,
        { key: slide.slideNumber, size: 'A4', style: styles.page },
        React.createElement(
          View,
          { style: styles.slideContainer },
          React.createElement(
            View,
            { style: styles.slideHeader },
            React.createElement(Text, { style: styles.slideNumber }, String(slide.slideNumber)),
            React.createElement(Text, { style: styles.slideTitle }, slide.title)
          ),
          React.createElement(Text, { style: styles.slideContent }, slide.prompt)
        ),
        React.createElement(
          Text,
          { style: styles.footer, fixed: true },
          'Generated by Nano Banana Slides Prompter'
        ),
        React.createElement(Text, {
          style: styles.pageNumber,
          fixed: true,
          render: ({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`,
        })
      )
    )
  );
}

/**
 * Export session slides to PDF format
 */
export async function exportToPdf(session: Session): Promise<void> {
  const slides = session.generatedPrompt?.slides || session.slides;
  if (slides.length === 0) {
    throw new Error('No slides to export');
  }

  // Create PDF document
  const doc = React.createElement(SlideDocument, { session, slides });
  const blob = await pdf(doc).toBlob();

  // Download the PDF
  const filename = sanitizeFilename(session.title, 'presentation');
  downloadBlob(blob, `${filename}.pdf`);
}

/**
 * Download blob as file
 */
function downloadBlob(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
