/**
 * PPTX Exporter
 * Exports slides to PowerPoint format using pptxgenjs
 */
import PptxGenJS from 'pptxgenjs';
import type { Session, ParsedSlide } from '@/types/slidePrompt';
import { sanitizeFilename } from '@/lib/utils/sanitize-filename';

interface PptxExportOptions {
  title?: string;
  author?: string;
  subject?: string;
}

/**
 * Export session slides to PPTX format
 */
export async function exportToPptx(
  session: Session,
  options: PptxExportOptions = {}
): Promise<void> {
  const slides = session.generatedPrompt?.slides || session.slides;
  if (slides.length === 0) {
    throw new Error('No slides to export');
  }

  const pptx = new PptxGenJS();

  // Set presentation properties
  pptx.title = options.title || session.title;
  pptx.author = options.author || 'Nano Banana Slides Prompter';
  pptx.subject = options.subject || 'AI-Generated Slide Prompts';

  // Create title slide
  const titleSlide = pptx.addSlide();
  titleSlide.addText(session.title, {
    x: 0.5,
    y: 2,
    w: '90%',
    h: 1,
    fontSize: 36,
    bold: true,
    align: 'center',
    color: '363636',
  });
  titleSlide.addText(`${slides.length} Slides • Generated by Nano Banana`, {
    x: 0.5,
    y: 3.5,
    w: '90%',
    h: 0.5,
    fontSize: 14,
    align: 'center',
    color: '666666',
  });

  // Create content slides
  for (const slide of slides) {
    const pptxSlide = pptx.addSlide();

    // Slide title
    pptxSlide.addText(`Slide ${slide.slideNumber}: ${slide.title}`, {
      x: 0.5,
      y: 0.3,
      w: '90%',
      h: 0.8,
      fontSize: 24,
      bold: true,
      color: '363636',
    });

    // Slide content (prompt)
    pptxSlide.addText(slide.prompt, {
      x: 0.5,
      y: 1.3,
      w: '90%',
      h: 4,
      fontSize: 14,
      color: '444444',
      valign: 'top',
    });
  }

  // Generate and download
  const filename = sanitizeFilename(session.title, 'presentation');
  await pptx.writeFile({ fileName: `${filename}.pptx` });
}
