/**
 * PdfPreview Component
 * Modal for previewing PDF before download with HTML-based preview
 */
import { useState, useMemo, Suspense } from 'react';
import { useTranslation } from 'react-i18next';
import { Download, ChevronLeft, ChevronRight, X, Loader2, FileText } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import type { Session } from '@/types/slidePrompt';

// Theme colors extracted as constants for maintainability
const THEME = {
  primary: 'bg-blue-500',
  titleText: 'text-gray-900',
  contentText: 'text-gray-700',
  mutedText: 'text-gray-500',
  border: 'border-gray-200',
  pageBg: 'bg-gray-100 dark:bg-gray-900',
  cardBg: 'bg-white',
} as const;

interface PdfPreviewProps {
  session: Session;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onDownload: () => void;
}

export function PdfPreview({ session, open, onOpenChange, onDownload }: PdfPreviewProps) {
  const { t } = useTranslation();
  const [currentPage, setCurrentPage] = useState(1);

  const slides = useMemo(() => session.generatedPrompt?.slides || session.slides || [], [session]);

  const totalPages = slides.length + 1; // +1 for title page

  const handlePrevPage = () => {
    setCurrentPage((p) => Math.max(1, p - 1));
  };

  const handleNextPage = () => {
    setCurrentPage((p) => Math.min(totalPages, p + 1));
  };

  const handleDownload = () => {
    onDownload();
    onOpenChange(false);
  };

  if (slides.length === 0) {
    return null;
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-hidden flex flex-col p-0">
        <DialogHeader className="px-6 py-4 border-b">
          <div className="flex items-center justify-between">
            <DialogTitle className="flex items-center gap-2">
              <FileText className="h-5 w-5 text-primary" />
              {t('pdfPreview.title', 'PDF Preview')}
            </DialogTitle>
            <div className="flex items-center gap-2">
              <Button variant="outline" size="sm" onClick={handleDownload}>
                <Download className="h-4 w-4 mr-2" />
                {t('pdfPreview.download', 'Download PDF')}
              </Button>
              <Button variant="ghost" size="icon" onClick={() => onOpenChange(false)}>
                <X className="h-4 w-4" />
              </Button>
            </div>
          </div>
        </DialogHeader>

        {/* PDF Viewer - HTML-based preview */}
        <div className="flex-1 overflow-hidden bg-muted/30">
          <Suspense
            fallback={
              <div className="flex items-center justify-center h-full">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
                <span className="ml-2">{t('pdfPreview.loading', 'Loading preview...')}</span>
              </div>
            }
          >
            <div className="h-full w-full">
              <div
                className={`h-[60vh] w-full flex items-center justify-center ${THEME.pageBg} overflow-auto p-4`}
              >
                <div className={`${THEME.cardBg} shadow-lg rounded-lg p-8 max-w-2xl w-full`}>
                  {currentPage === 1 ? (
                    // Title page preview
                    <div className="text-center py-16">
                      <h1 className={`text-3xl font-bold ${THEME.titleText} mb-4`}>
                        {session.title}
                      </h1>
                      <p className={THEME.mutedText}>
                        {slides.length} Slides • Generated by Nano Banana Slides Prompter
                      </p>
                    </div>
                  ) : (
                    // Slide content preview
                    <div>
                      <div
                        className={`flex items-center gap-3 mb-4 pb-3 border-b-2 ${THEME.border}`}
                      >
                        <span className={`${THEME.primary} text-white px-3 py-1 rounded font-bold`}>
                          {slides[currentPage - 2]?.slideNumber}
                        </span>
                        <h2 className={`text-xl font-bold ${THEME.titleText}`}>
                          {slides[currentPage - 2]?.title}
                        </h2>
                      </div>
                      <pre className={`text-sm ${THEME.contentText} whitespace-pre-wrap font-mono`}>
                        {slides[currentPage - 2]?.prompt}
                      </pre>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </Suspense>
        </div>

        {/* Page navigation */}
        <div className="px-6 py-3 border-t flex items-center justify-between bg-background">
          <Button variant="outline" size="sm" onClick={handlePrevPage} disabled={currentPage <= 1}>
            <ChevronLeft className="h-4 w-4 mr-1" />
            {t('pdfPreview.prev', 'Previous')}
          </Button>
          <span className="text-sm text-muted-foreground">
            {t('pdfPreview.pageOf', 'Page {{current}} of {{total}}', {
              current: currentPage,
              total: totalPages,
            })}
          </span>
          <Button
            variant="outline"
            size="sm"
            onClick={handleNextPage}
            disabled={currentPage >= totalPages}
          >
            {t('pdfPreview.next', 'Next')}
            <ChevronRight className="h-4 w-4 ml-1" />
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
